NUMPY MATRIZ IMPORTANDO MODULO:

pip install numpy: para instalar el paquete, solo se hace una vez
import numpy as np: ya instalado podemos importarlo con el alias np, cada vez que se necesite utilizar el metodo o modulo
from numpy import random: generar datos aleatorios

In [95]:
import numpy as np
arr = np.array(78) # array 0-D 
print(arr)
print("Dimensiones=", arr.ndim)

78
Dimensiones= 0


In [ ]:
lista = [1,2,3,4,5,6,7]
arreglo = np.array(lista)

print (lista)
# arreglo es como una forma de matriz de vectores
print (arreglo)

[1, 2, 3, 4, 5, 6, 7]
[1 2 3 4 5 6 7]


In [ ]:
import numpy as np #importamos el método numpy

CREACION DE arrays con RANDOM

In [96]:
import numpy as np
from numpy import random # random: no se pueden predecir son aleatorios se debe especificar el SIZE en forma de dupla ()

arr1 = random.randint(100, size=(2,3)) #LA TUPLA ES (fila, columna)
# randint matrices con valores numericos enteros
print(arr1)
print("Dimensiones=", arr1.ndim)
print("Cuantos elementos tiene =", arr1.shape)
print("me muestra el valor del array=", arr1[0,2])# es la forma de recorrer el array y traer los datos 
print("me muestra el valor del array=", arr1[1,2])

[[17 30 18]
 [25 54 73]]
Dimensiones= 2
Cuantos elementos tiene = (2, 3)
me muestra el valor del array= 18
me muestra el valor del array= 73


In [ ]:
arr2 = random.rand(3,3) # hasta el numero que el debe seleccionar este seria un array 1-D = unidemensional
# rand para valores numericos con decimales
print(arr2)
print("Dimensiones=", arr2.ndim)
print("Cuantos elementos tiene =", arr2.shape)
print("me muestra un valor en la posición de dicho array=", arr2[0,0])

[[0.27567811 0.48128514 0.63794252]
 [0.1285024  0.17051793 0.05855639]
 [0.92820941 0.31368009 0.54511066]]
Dimensiones= 2
Cuantos elementos tiene = (3, 3)
me muestra un valor en la posición de dicho array= 0.27567811219334626


In [ ]:
arr3 = random.rand(5) # hasta el numero que el debe seleccionar, DIMENSIONES = 2-D
# rand para valores numericos con decimales
print(arr3)
print("Dimensiones=", arr3.ndim)
print("Cuantos elementos tiene =", arr3.shape)
print("me muestra un valor en la posición de dicho array=", arr3[0])
print("me muestra un valor en la posición de dicho array=", arr3[1])
print("me muestra el valor de la fila del array=", arr3[1])
print("me muestra las posiciones =", arr3[0:3]) #slyer
print("me muestra las posiciones saltadas =", arr3[0:4:2]) #slyer
print("me muestra el último valor del array=", arr3[-1])

[0.86548893 0.05146784 0.22458739 0.50364981 0.31695884]
Dimensiones= 1
Cuantos elementos tiene = (5,)
me muestra un valor en la posición de dicho array= 0.865488932481187
me muestra un valor en la posición de dicho array= 0.051467844963127174
me muestra el valor de la fila del array= 0.051467844963127174
me muestra las posiciones = [0.86548893 0.05146784 0.22458739]
me muestra las posiciones saltadas = [0.86548893 0.22458739]
me muestra el último valor del array= 0.31695883574409367


In [ ]:
arr4 = random.choice([1,2,54,9], p=[0.1,0.5,0.3,0.1], size=(5,5)) #array unidemensional
#choice para selecci10onar unos valores desde un listado
#p = la probabilidad que tiene cada uno de los datos del array
print(arr4)
print("Dimensiones=", arr4.ndim)

[[ 9  2  9 54  1]
 [ 2  2  2  9  2]
 [ 2  2 54  2  2]
 [ 2  2  1  2  2]
 [ 2  2  9  1 54]]
Dimensiones= 2


In [ ]:
print("array")
print(arr)
print("Dimensiones=", arr.ndim)
print("Cuantos elementos tiene =", arr.shape)
print(" ")
print("array 1")
print(arr1)
print("Dimensiones=", arr1.ndim)
print("Cuantos elementos tiene =", arr1.shape)
print("me muestra el valor fila cero columna 2 del array=", arr1[0,2])# es la forma de recorrer el array y traer los datos 
print("me muestra el valor fila uno columna 2 del array=", arr1[1,2])

print(" ")
print("array 2")
print(arr2)
print("Dimensiones=", arr2.ndim)
print("Cuantos elementos tiene =", arr2.shape)
print("me muestra un valor en la posición de dicho array=", arr2[0,0])
print(" ")
print("array 3")
print(arr3)
print("Dimensiones=", arr3.ndim)
print("Cuantos elementos tiene =", arr3.shape)
print("me muestra un valor en la posición cero de dicho array=", arr3[0])
print("me muestra un valor en la posición uno de dicho array=", arr3[1])
print("me muestra el valor de la fila del array=", arr3[1])
print("me muestra las posiciones =", arr3[0:3]) #slyer
print("me muestra las posiciones saltadas =", arr3[0:4:2]) #slyer
print("me muestra el último valor del array=", arr3[-1])

array
78
Dimensiones= 0
Cuantos elementos tiene = ()
 
array 1
[[15  1 67]
 [51 25 33]]
Dimensiones= 2
Cuantos elementos tiene = (2, 3)
me muestra el valor fila cero columna 2 del array= 67
me muestra el valor fila uno columna 2 del array= 33
 
array 2
[[0.27567811 0.48128514 0.63794252]
 [0.1285024  0.17051793 0.05855639]
 [0.92820941 0.31368009 0.54511066]]
Dimensiones= 2
Cuantos elementos tiene = (3, 3)
me muestra un valor en la posición de dicho array= 0.27567811219334626
 
array 3
[0.86548893 0.05146784 0.22458739 0.50364981 0.31695884]
Dimensiones= 1
Cuantos elementos tiene = (5,)
me muestra un valor en la posición cero de dicho array= 0.865488932481187
me muestra un valor en la posición uno de dicho array= 0.051467844963127174
me muestra el valor de la fila del array= 0.051467844963127174
me muestra las posiciones = [0.86548893 0.05146784 0.22458739]
me muestra las posiciones saltadas = [0.86548893 0.22458739]
me muestra el último valor del array= 0.31695883574409367


In [ ]:
print(arr1.dtype)
print(arr3.dtype)
print(arr1.shape)
print(arr3.shape)
print("")
arr3_s = arr3.astype('S')
print("ANTES=", arr3.dtype, arr3)
print("AHORA=",arr3_s.dtype, arr3_s)
print("Cuantos elementos tiene =", arr3_s.shape)
print("")
print(arr1.shape)
print(arr1)
print("haciendo un reshape")
print(arr1.reshape(3,2))

int64
float64
(2, 3)
(5,)

ANTES= float64 [0.86548893 0.05146784 0.22458739 0.50364981 0.31695884]
AHORA= |S32 [b'0.865488932481187' b'0.051467844963127174' b'0.2245873945431427'
 b'0.5036498074689191' b'0.31695883574409367']
Cuantos elementos tiene = (5,)

(2, 3)
[[15  1 67]
 [51 25 33]]
haciendo un reshape
[[15  1]
 [67 51]
 [25 33]]


OPERACIONES ARITMETICAS CON ARRAY

In [ ]:
m = random.randint(10, size=(3,5)) # DEBEN SER IGUALES
n = random.randint(10, size=(3,5))

print(m)
print(n)
print("")
print("SUMA")
print(m+n)
print("")
print("MULTIPLICACION")
print(m*n)

[[2 9 0 5 5]
 [8 5 1 1 7]
 [6 4 8 4 2]]
[[9 0 5 7 2]
 [0 3 6 3 8]
 [4 2 2 8 6]]

SUMA
[[11  9  5 12  7]
 [ 8  8  7  4 15]
 [10  6 10 12  8]]

MULTIPLICACION
[[18  0  0 35 10]
 [ 0 15  6  3 56]
 [24  8 16 32 12]]


OPERACIONES CON ARRAY: SEPARAR Y ORDENAR

In [ ]:
newarr = np.array_split(m,3) # separar es la operación inversa de unir con array_split divide las filas
print(newarr)

[array([[2, 9, 0, 5, 5]]), array([[8, 5, 1, 1, 7]]), array([[6, 4, 8, 4, 2]])]


In [ ]:
newarr = np.sort(m) # ordenar de mayor a menor los datos del array
print("antes")
print(m)
print("después")
print(newarr)

antes
[[2 9 0 5 5]
 [8 5 1 1 7]
 [6 4 8 4 2]]
después
[[0 2 5 5 9]
 [1 1 5 7 8]
 [2 4 4 6 8]]


OPERACIONES ARRAY: CONCATENAR Y APILAR

In [ ]:
newarr = np.concatenate((m,n), axis =1) # concatenar dos arreglos en uno solo
print("antes")
print(m)
print(n)
print("después concatenado")
print(newarr)

antes
[[2 9 0 5 5]
 [8 5 1 1 7]
 [6 4 8 4 2]]
[[9 0 5 7 2]
 [0 3 6 3 8]
 [4 2 2 8 6]]
después concatenado
[[2 9 0 5 5 9 0 5 7 2]
 [8 5 1 1 7 0 3 6 3 8]
 [6 4 8 4 2 4 2 2 8 6]]


In [ ]:
newarr2 = np.stack((m,n), axis =1) # apilar unir en diferente eje con stack
print("antes")
print(m)
print(n)
print("después apilado")
print(newarr2)

antes
[[2 9 0 5 5]
 [8 5 1 1 7]
 [6 4 8 4 2]]
[[9 0 5 7 2]
 [0 3 6 3 8]
 [4 2 2 8 6]]
después apilado
[[[2 9 0 5 5]
  [9 0 5 7 2]]

 [[8 5 1 1 7]
  [0 3 6 3 8]]

 [[6 4 8 4 2]
  [4 2 2 8 6]]]


OPERACIONES CON ARRAYS: FILTRAR Y BUSCAR

In [ ]:
arr3 = np.array([41,42,43,44]) # filtrando
filter_arr3 = arr3 > 42
newarr3 = arr3[filter_arr3]
print("antes")
print(arr3)
print("filtrando mayores de 42")
print(newarr3)

antes
[41 42 43 44]
filtrando mayores de 42
[43 44]


In [ ]:
arr3 = np.array([5,6,7,48]) # filtrando
x = np.where(arr3 == 48)
print("arreglo")
print(arr3)
print("filtrando 48:")
print("esta en la posición", x)
print("el valor es", arr3[x])
print("")
x2 = np.where(arr3 <= 10)
print("esta en la posición", x2)
print("el valor es", arr3[x2])

arreglo
[ 5  6  7 48]
filtrando 48:
esta en la posición (array([3]),)
el valor es [48]

esta en la posición (array([0, 1, 2]),)
el valor es [5 6 7]


#Insert the correct argument for creating a NumPy array with 2 dimensions.

In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=2) 
print(arr)

[[1 2 3 4]]


#Inserte la sintaxis de corte correcta para imprimir la siguiente selección de la matriz:

Todo desde (incluido) el segundo elemento hasta (sin incluir) el quinto elemento.

In [ ]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr[1:4])

[15 20 25]


#Inserte la sintaxis de corte correcta para imprimir la siguiente selección de la matriz:

Todo desde (incluido) el tercer elemento hasta (sin incluir) el quinto elemento.

In [ ]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr[2:4])

[20 25]


Inserte la sintaxis de corte correcta para imprimir la siguiente selección de la matriz:

Cada otro elemento desde (incluido) el segundo elemento hasta (sin incluir) el quinto elemento.

Consejo: utilice la sintaxis de pasos.

In [ ]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr[2:7:4]) # 1er dato donde inicia, 2do dato hasta donde va y 3er dato el salto entre numeros del arreglo

[20 40]


Inserte la sintaxis de corte correcta para imprimir la siguiente selección de la matriz:

Todos los demás elementos de toda la matriz.

Consejo: utilice la sintaxis de pasos.

In [ ]:
arr = np.array([10, 15, 20, 25, 30, 35, 40]) # arranca en la posición 1 y se va de dos en dos

print(arr[1::2])

[15 25 35]


In [ ]:
arr = np.array([10, 15, 20, 25, 30, 35, 40]) # arranca en posicion cero y se va de dos en dos

print(arr[::2])

[10 20 30 40]


In [ ]:
arr = np.array([1, 2, 3, 4]) 

print(arr.dtype) # ver el tipo de dato

int64


In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)

[b'1' b'2' b'3' b'4']


In [ ]:
arr = np.array([1.1, 2.1, 3.1]) 
newarr = arr.astype('i') #Inserte el método correcto para cambiar el tipo de datos a entero.
print("Decimales",arr)
print("A enteros",newarr)


Decimales [1.1 2.1 3.1]
A enteros [1 2 3]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy() # método para copiar un arreglo

print(arr)
print(x)


[1 2 3 4 5]
[1 2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.view() # el método correcto para hacer una vista de la matriz.

print(x)


[1 2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

print("la matriz tiene",arr.shape, "elementos") # metodo para comprobar la cantidad de elementos de una matriz

la matriz tiene (6,) elementos


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3) #método para remodelar el arreglo
print(arr)
print("")
print(newarr,"  3 columnas y 4 filas")

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]   3 columnas y 4 filas


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], ndmin=3)

newarr = arr.reshape(-1) # cambiar de 3d a 1d
print(arr, "  en 3D")
print("")
print(newarr,"  en 1D")


[[[ 1  2  3  4  5  6  7  8  9 10 11 12]]]   en 3D

[ 1  2  3  4  5  6  7  8  9 10 11 12]   en 1D


# PANDAS

In [81]:
pip install pandas

In [98]:
import pandas as pd # importar el método pandas

col = pd.Series([1,2,3])

print(col)
print("")

import numpy as np
from numpy import random  #importar el método random

col2 = pd.Series(random.rand(5))
print(col2)


0    1
1    2
2    3
dtype: int64

0    0.128942
1    0.778461
2    0.355399
3    0.844690
4    0.859128
dtype: float64


# dataframes

In [100]:
df = pd.DataFrame ({"nombre": ["andres", "mitch", "kathe"], "notas": [5, 4, 3]})

print(df)

   nombre  notas
0  andres      5
1   mitch      4
2   kathe      3
